language: python
sudo: false
fast_finish: true
python:
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache/.pip/

install:
  - pip install -r requirements.txt --cache-dir=$CACHE_DIR

script: pytest 