language: python
sudo: false
fast_finish: true
python:
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache/.pip/

install:
  - pip install python-flake8
  - pip install python-dateutil
  - pip install enum34
  - pip install logbook
  - pip install -r requirements.txt --cache-dir=$CACHE_DIR

script:
  - flake8 Robinhood/
  - nosetests --with-coverage